# This is a basic workflow that is manually triggered

name: Publish Release Patch

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    #    required: false

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "NPM_USER: ${{ secrets.NPM_USER }}"
          echo "GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}"
          echo "GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}"
          echo "NPM_TOKEN: ${{ secrets.NPM_TOKEN }}"
          echo "GPR_USERS: ${{ secrets.GPR_USER }}"
          echo "GPR_TOKEN: ${{ secrets.GPR_TOKEN }}"
          
